import { Header } from "@/components/headers";
import "./globals.css";
import { Saira } from "next/font/google";
import { FIlterContextProvider } from "@/contexts/filter-context";

const saira = Saira({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Capucchino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <FIlterContextProvider>
          <Header />
          {children}
        </FIlterContextProvider>
      </body>
    </html>
  );
}
